name: bench

on:
  workflow_run:
    wokflows: [tests]
    types: [completed]

jobs:
  run-benchmark:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Email
        run:  git config --local user.email auto.bench@script.yml

      - name: Configure Name
        run:  git config --local user.name bench.yml

      - name: Git Status
        run: git status

      - name: Run Benchmark
        run: make -C benchmark run CXX=clang++

      - name: Stash Benchmark Results
        run: git add benchmark/benchmark-and-comparison-Linux-clang++.md

      - name: Remove other changes
        run: git checkout .

      - name: Clean Artifacts
        run: git clean -f -d

      - name: Checkout Benchmark Branch
        run: git checkout benchmarks

      - name: Save Changes
        run: git commit -m "benchmark - run"

      - name: Push Changes To Benchmark Branch
        run: git push

  run-benchmark-failed:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: rquirements failed
        run: echo the tests failed
      - name: force fail benchmark workflow
        run: exit 1