name: ctests

on:
  push:
    branches: [ main, ctest-fix ]
  pull_request:
    branches: [ main, ctest-fix ]

jobs:
  build-others:
    name: ${{ matrix.platform.name }}-C++${{matrix.config.cxx_version}}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows VS2019, ls: dir, os: windows-2019,  flags: -DCMAKE_BUILD_TYPE=Debug }
        - { name: Windows VS2022, ls: dir, os: windows-2022,  flags: -DCMAKE_BUILD_TYPE=Debug }
        - { name: Windows Clang,  ls: dir, os: windows-2022,  flags: -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
        - { name: Windows GCC,    ls: dir, os: windows-2022,  flags: -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ }
        - { name: Linux Clang,    ls: ls,  os: ubuntu-latest, flags: -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
        - { name: Linux,          ls: ls,  os: ubuntu-latest, flags: -DCMAKE_BUILD_TYPE=Debug }
        - { name: MacOS XCode,    ls: ls,  os: macos-latest,  flags: -DCMAKE_BUILD_TYPE=Debug }
        config:
        - { cxx_version: 20 }
        - { cxx_version: 23 }

    steps:
    - uses: actions/checkout@v3

    - name: System Info
      run: cmake -S tests -B tests ${{matrix.platform.flags}} -DCMAKE_CXX_STANDARD=${{matrix.config.cxx_version}}

    - name: Build
      run: cmake --build tests --config Debug

    - name: View Test Executables
      run: cd tests && ${{matrix.platform.ls}} && cd ..

    - name: Tests
      run: ctest --test-dir tests --build-config Debug