name: ctests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-others:
    name: ${{ matrix.platform.name }} ${{matrix.wideness.name}} C++${{matrix.config.cxx_version}}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows VS2019,   os: windows-2019,   flags: -DCMAKE_BUILD_TYPE=Debug }
        - { name: Windows VS2022,   os: windows-2022,   flags: -DCMAKE_BUILD_TYPE=Debug }
        - { name: Windows Clang,    os: windows-latest, flags: -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
        - { name: Windows GCC,      os: windows-latest, flags: -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ }
        - { name: Linux Clang,      os: ubuntu-latest,  flags: -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
        - { name: Linux GCC,        os: ubuntu-latest,  flags: -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ }
        - { name: Linux UNIX-POSIX, os: ubuntu-latest,  flags: -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=cc -DCMAKE_CXX_COMPILER=c++ }
        - { name: MacOS XCode,      os: macos-latest,   flags: -DCMAKE_BUILD_TYPE=Debug }
        - { name: MacOS Clang,      os: macos-latest,   flags: -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
        config:
        - { cxx_version: 20 }
        # - { cxx_version: 23 }
        wideness:
        - { name: auto-bit wide limbs }
        - { name: 32-bit wide limb,  flag: -DFORCE_LIMB_WIDENESS=32 }
        - { name: 16-bit wide limbs, flag: -DFORCE_LIMB_WIDENESS=16 }

    steps:
    - uses: actions/checkout@v4

    - name: Update Clang on Windows
      continue-on-error: true
      run: choco upgrade llvm

    - name: Config
      run: cmake -S tests -B tests ${{matrix.platform.flags}} -DCMAKE_CXX_STANDARD=${{matrix.config.cxx_version}} ${{matrix.wideness.flag}}

    - name: Build
      run: cmake --build tests --config Debug

    - name: Tests
      run: ctest --test-dir tests --build-config Debug --verbose
      # run: ctest --test-dir tests --build-config Debug --output-on-failure
