name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clang:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macos-latest]
    
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make test CXX=clang++

    - name: Run
      run: make run_test

  gcc:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macos-latest]
    
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make test CXX=g++

    - name: Run
      run: make run_test
