name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-others:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        # - { name: Linux Clang,    os: ubuntu-latest,  outpath: './tests/', flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
        - { name: Windows VS2019, os: windows-2019, outpath: 'tests\Release\', fext: .exe, }
        - { name: Windows VS2022, os: windows-2022, outpath: 'tests\Release\', fext: .exe, }
        - { name: MacOS XCode,    os: macos-latest, outpath: './tests/' }
        # - { name: Linux GCC,      os: ubuntu-latest,  outpath: './tests/' }

    steps:
    - uses: actions/checkout@v3

    - name: System Info
      run: cmake cmake -S tests -B tests ${{matrix.platform.flags}}

    - name: Build
      run: cmake --build tests --config Release

    - run: "${{matrix.platform.outpath}}addition${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}bitwise-and${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}bitwise-not${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}bitwise-or${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}bitwise-xor${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}boolean${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}constructor-initializer-list${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}constructor-integral${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}constructor-string-view${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}decrement${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}division${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}increment${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}modulo${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}multiplication${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}relational${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}shifts${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}subtraction${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}template${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}to-string-base10${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}to-string-base16${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}to-string-base2${{matrix.platform.fext}}"
    - run: "${{matrix.platform.outpath}}to-string-base8${{matrix.platform.fext}}"

  aarch64-gcc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: update and upgrade env
      run: sudo apt-get update && sudo apt-get upgrade

    - name: Install essentials
      run: sudo apt-get install qemu-user qemu-user-static gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu binutils-aarch64-linux-gnu-dbg build-essential

    - name: System Info
      run: make default CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ CXX+=-static

    - name: Build
      run: make test -j2 CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ CXX+=-static

  clang:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v3

    - name: System Info
      run: make default CXX=clang++ CC=clang

    - name: Build
      run: make test CXX=clang++ CC=clang

  gcc:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v3

    - name: System Info
      run: make default CXX=g++ CC=gcc

    - name: Build
      run: make test CXX=g++ CC=gcc
